apiVersion: v1
kind: Pod
metadata:
  name: ccbot
  labels:
    name: ccbot
spec:
  containers:
    - name: ccbot
      image: timkoopmans/ccbot:latest
      imagePullPolicy: Never
      env:
        - name: OPENAI_API_KEY
          valueFrom:
            secretKeyRef:
              name: ccbot-secrets
              key: openai-api-key
        - name: TZ
          value: Australia/Melbourne
        - name: PYTHONUNBUFFERED
          value: "1"
        - name: REDIS_HOST
          value: latest-redis-master.default.svc.cluster.local
        - name: REDIS_PORT
          value: "6379"
        - name: REDIS_PASSWORD
          valueFrom:
            secretKeyRef:
              name: latest-redis
              key: redis-password
